//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Scripts/Inputs/GUIInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GUIInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GUIInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GUIInputs"",
    ""maps"": [
        {
            ""name"": ""PlayerUI"",
            ""id"": ""6fc2c0ab-56e7-4e11-b895-72b99eb33ade"",
            ""actions"": [
                {
                    ""name"": ""HotbarNumbers"",
                    ""type"": ""Button"",
                    ""id"": ""314c2d44-5bd9-424f-888d-809284fcfdb3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HotbarMouseScroll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dd6ca3a4-d705-4a84-aff3-b7346fbc012d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5cf93533-cae8-4d34-a807-82d22da5ffab"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": ""Scale"",
                    ""groups"": """",
                    ""action"": ""HotbarNumbers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de760199-45fa-41ca-abe7-88657ab91afa"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=2)"",
                    ""groups"": """",
                    ""action"": ""HotbarNumbers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bb00f6c-7f07-4dd9-98d1-e480303aeecf"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=3)"",
                    ""groups"": """",
                    ""action"": ""HotbarNumbers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3567c38f-fcea-447c-96f7-568cbe4e71fc"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=4)"",
                    ""groups"": """",
                    ""action"": ""HotbarNumbers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6870c137-1f41-44a2-a2b2-902a7d4da8ad"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=5)"",
                    ""groups"": """",
                    ""action"": ""HotbarNumbers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c5868aa-bb21-4e22-b99d-d29eeda05e7b"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=6)"",
                    ""groups"": """",
                    ""action"": ""HotbarNumbers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b93c7909-b782-4d8a-85a2-e92299a2c91e"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=7)"",
                    ""groups"": """",
                    ""action"": ""HotbarNumbers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92ea9f00-e5ed-4ce2-901c-1301d39aa4f6"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=8)"",
                    ""groups"": """",
                    ""action"": ""HotbarNumbers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b9ffa1a-5901-4ae7-987d-f6f8b6aa4ee8"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=9)"",
                    ""groups"": """",
                    ""action"": ""HotbarNumbers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9460d9e-ac2b-4cb5-a56a-94deb1ae623a"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotbarMouseScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerUI
        m_PlayerUI = asset.FindActionMap("PlayerUI", throwIfNotFound: true);
        m_PlayerUI_HotbarNumbers = m_PlayerUI.FindAction("HotbarNumbers", throwIfNotFound: true);
        m_PlayerUI_HotbarMouseScroll = m_PlayerUI.FindAction("HotbarMouseScroll", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerUI
    private readonly InputActionMap m_PlayerUI;
    private IPlayerUIActions m_PlayerUIActionsCallbackInterface;
    private readonly InputAction m_PlayerUI_HotbarNumbers;
    private readonly InputAction m_PlayerUI_HotbarMouseScroll;
    public struct PlayerUIActions
    {
        private @GUIInputs m_Wrapper;
        public PlayerUIActions(@GUIInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @HotbarNumbers => m_Wrapper.m_PlayerUI_HotbarNumbers;
        public InputAction @HotbarMouseScroll => m_Wrapper.m_PlayerUI_HotbarMouseScroll;
        public InputActionMap Get() { return m_Wrapper.m_PlayerUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerUIActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerUIActions instance)
        {
            if (m_Wrapper.m_PlayerUIActionsCallbackInterface != null)
            {
                @HotbarNumbers.started -= m_Wrapper.m_PlayerUIActionsCallbackInterface.OnHotbarNumbers;
                @HotbarNumbers.performed -= m_Wrapper.m_PlayerUIActionsCallbackInterface.OnHotbarNumbers;
                @HotbarNumbers.canceled -= m_Wrapper.m_PlayerUIActionsCallbackInterface.OnHotbarNumbers;
                @HotbarMouseScroll.started -= m_Wrapper.m_PlayerUIActionsCallbackInterface.OnHotbarMouseScroll;
                @HotbarMouseScroll.performed -= m_Wrapper.m_PlayerUIActionsCallbackInterface.OnHotbarMouseScroll;
                @HotbarMouseScroll.canceled -= m_Wrapper.m_PlayerUIActionsCallbackInterface.OnHotbarMouseScroll;
            }
            m_Wrapper.m_PlayerUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @HotbarNumbers.started += instance.OnHotbarNumbers;
                @HotbarNumbers.performed += instance.OnHotbarNumbers;
                @HotbarNumbers.canceled += instance.OnHotbarNumbers;
                @HotbarMouseScroll.started += instance.OnHotbarMouseScroll;
                @HotbarMouseScroll.performed += instance.OnHotbarMouseScroll;
                @HotbarMouseScroll.canceled += instance.OnHotbarMouseScroll;
            }
        }
    }
    public PlayerUIActions @PlayerUI => new PlayerUIActions(this);
    public interface IPlayerUIActions
    {
        void OnHotbarNumbers(InputAction.CallbackContext context);
        void OnHotbarMouseScroll(InputAction.CallbackContext context);
    }
}
